import Image from 'next/image'
import './globals.css'
import Link from 'next/link'

export const metadata = {
  title: 'homepage',
  description: 'Generated by syw',
}

export default async function RootLayout({ children }) {
const resp = await fetch('http://localhost:9999/topics', {cache: 'no-store'});
const topics = await resp.json();
<link href='https://cdn.jsdelivr.net/gh/Project-Noonnu/noonfonts_2107@1.1/Pretendard-Regular.woff' rel='stylesheet'></link>
  return (
    <html>
      <body>
      {children}
      <div class="image-container">
        <div class="text-overlay">
          <p>content</p>
        </div>
        <img src="/b.n.image.png"/>
      </div>
      <div class="bar">
        <li><a href="/">Notice</a></li>
        <li><a href="/">Contact NSLab</a></li>
      </div>
      <p>Notice</p>
      <ol className="content">
          {topics.map((topic)=>{
            return <li key={topics.id}>
              <Link href={`/read/${topic.id}`}>{topic.title}</Link>
              <span>Written by:{topic.written_by}</span>
              <span>date:{topic.date}</span>
            </li>
          })}
      </ol>
      </body>
    </html>
  )
}
